version: "3"

volumes:
    pg-data:

services:

    kibana-opendrr:
        image: docker.elastic.co/kibana/kibana:7.16.1
        
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch-opendrr:9200

        ports: 
            - 5601:5601
        
        depends_on: 
            - elasticsearch-opendrr
    
    elasticsearch-opendrr: 
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
        
        environment:
            - discovery.type=single-node
        
        ports: 
            - 9200:9200
    
    pygeoapi-opendrr:
        image: opendrr-pygeoapi
        build: ./pygeoapi
        
        ports:
            - 5001:80
        
        depends_on:
            - elasticsearch-opendrr
        
        restart: unless-stopped
    
    db-opendrr:
        image: opendrr-postgis
        build: ./postgis

        command: >
            -c checkpoint_timeout=1d
            -c max_wal_size=256GB
            -c synchronous_commit=off

        shm_size: '1gb'
 
        env_file:
            - .env
        
        volumes: 
            - pg-data:/var/lib/postgresql

        ports: 
            - ${POSTGRES_PORT}:5432

        environment: 
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASS: ${POSTGRES_PASS}
            POSTGRES_DB: ${DB_NAME}
        
        restart: on-failure
