
title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[allowlist]
description = "Allow list for sample (but invalid) GitHub tokens"
regexTarget = "match"
regexes = [
  '''^ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$''',
]
